const express=require('express')
const { registerUser, fetchUsers, fetchUserbyid, deleteUser, updateUser, userLogin, addCart, viewCart, placeOrder, UserOrderview,} = require('../controller/usercntrl')
const Verfiytoken = require('../Authentication/verifytoken')
const userRouter=express.Router()
userRouter.post("/reg",registerUser)
userRouter.get("/hi",fetchUsers)
userRouter.get('/hum',fetchUserbyid)
userRouter.delete('/deluser',deleteUser)
userRouter.put('/update',updateUser)
userRouter.post("/login",userLogin)
userRouter.post("/addtocart",addCart)
userRouter.get('/cartitems',viewCart)
userRouter.post('/placeorder',placeOrder)
userRouter.get('/vieworder',UserOrderview)
module.exports=userRouter;